### ISSUE TITLE
Error encountered while parsing `definitions.h` on trying to make a plot (2D cartesian geometry)

### ISSUE THREAD

**Issue by dutta-alankar** [neutrinoceros/yt_idefix#244]
I' attaching the python script and the data file that generates this error here as a [GDrive link](https://drive.google.com/file/d/12IIA_LOFwZhD_MHA-M6Q-21applEQFpD/view?usp=sharing).

```
Traceback (most recent call last):
  File "/home/alankar/Documents/myrepos/data-pluto/tests/lecoanet/test.py", line 4, in <module>
    ds = yt.load("./data.%04d.dbl.h5"%60)
  File "/home/alankar/Documents/myrepos/yt_idefix/venv/lib/python3.9/site-packages/yt/loaders.py", line 107, in load
    return candidates[0](fn, *args, **kwargs)
  File "/home/alankar/Documents/myrepos/yt_idefix/yt_idefix/data_structures.py", line 342, in __init__
    super().__init__(
  File "/home/alankar/Documents/myrepos/yt_idefix/venv/lib/python3.9/site-packages/yt/data_objects/static_output.py", line 261, in __init__
    self._parse_parameter_file()
  File "/home/alankar/Documents/myrepos/yt_idefix/yt_idefix/data_structures.py", line 857, in _parse_parameter_file
    super()._parse_parameter_file()
  File "/home/alankar/Documents/myrepos/yt_idefix/yt_idefix/data_structures.py", line 519, in _parse_parameter_file
    super()._parse_parameter_file()
  File "/home/alankar/Documents/myrepos/yt_idefix/yt_idefix/data_structures.py", line 388, in _parse_parameter_file
    self._parse_definitions_header()
  File "/home/alankar/Documents/myrepos/yt_idefix/yt_idefix/data_structures.py", line 652, in _parse_definitions_header
    expr = re.sub(r"g_inputParam\[(\w+)\]", self._get_input_parameter, expr)
  File "/home/alankar/anaconda3/envs/test/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/alankar/Documents/myrepos/yt_idefix/yt_idefix/data_structures.py", line 662, in _get_input_parameter
    return str(self.parameters["Parameters"][key])
KeyError: 'Parameters'
```

**Comment by dutta-alankar** [comment]
Got it! This is because `pluto.ini` is missing (attached here). Probably we should give a better and more helpful error message.
[pluto.ini.zip](https://github.com/neutrinoceros/yt_idefix/files/11108879/pluto.ini.zip)

**Comment by neutrinoceros** [comment]
> Got it! This is because pluto.ini is missing (attached here). Probably we should give a better and more helpful error message.

Agreed. We currently don't have a test for this case, I think we should start by adding one, and it should be possible to mock the situation without adding another data sample.

**Comment by neutrinoceros** [comment]
The simplest solution would be to issue a warning when no inifile was passed and we also couldn't find `pluto.ini`
